"""Add initial models

Revision ID: 01eb0c883698
Revises: 
Create Date: 2023-03-23 21:10:13.606018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eb0c883698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joke',
    sa.Column('joke_id', sa.UUID(), nullable=False),
    sa.Column('joke_content', sa.String(), nullable=True),
    sa.Column('joke_author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('joke_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joke')
    # ### end Alembic commands ###
